# Generated by Django 4.1.3 on 2023-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfood',
            name='fooditem',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderedFood',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
