# Generated by Django 4.1.3 on 2022-12-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='vendor_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
