# Generated by Django 4.1.3 on 2022-12-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='vendor_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
