# Generated by Django 4.1.3 on 2022-12-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_vendor_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='vendor_slug',
            new_name='restaurant_slug',
        ),
    ]
